// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"numbernama-go/handler"
	"numbernama-go/repo"
	"numbernama-go/service"
)

// Injectors from wire.go:

// InitializeMux builds the HTTP router via Google Wire.
func InitializeMux() (*mux.Router, error) {
	logger := provideLogger()
	server := provideSocketServer(logger)
	memoryGameplay := repo.NewMemoryGameplay()
	gameplayService := service.NewGameplayService(memoryGameplay)
	gameplaySocketHandler := handler.NewGameplaySocketHandler(gameplayService, memoryGameplay, logger)
	gameplayHandler := handler.NewGameplayHandler()
	userService := service.NewUserService()
	userSettingService := service.NewUserSettingService()
	router := assembleRouter(logger, server, gameplaySocketHandler, gameplayHandler, userService, userSettingService)
	return router, nil
}
